package com.ibrahimeshag.model;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@NoArgsConstructor
@AllArgsConstructor
@RequiredArgsConstructor
@Document(collection = "books")
public class Book {
    @Id                 // making this variable as ID, will be auto-generated by MongoDB
    private String id;

    @NonNull
    private Integer bookId;
    @NonNull
    private String name;
    @NonNull
    private String author;
    @NonNull
    private Double cost;

}
